trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/SolarSense.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    echo "Listando arquivos no diretório de fontes..."
    dir "$(Build.SourcesDirectory)"
  displayName: 'Listar arquivos no diretório de fontes'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    echo "Listando arquivos no diretório de artefatos..."
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Listar arquivos no diretório de artefatos'

# Publicar o pacote gerado como artefato
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Caminho onde o WebApp.zip foi gerado
    ArtifactName: 'drop'  # Nome do artefato
    publishLocation: 'Container'

# Baixar artefato para o estágio de deploy
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'drop'  # Nome do artefato publicado
    downloadPath: '$(Build.ArtifactStagingDirectory)'  # Caminho onde os artefatos serão baixados
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Enzo Lafer RM551111(8b3c71f1-34e5-4ca5-adde-1783ea3a7d68)'
    appType: 'webApp'
    appName: 'SolarSense'
    deployToSlotOrASE: true
    resourceGroupName: 'GS_SOLARSENSE'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/WebApp.zip'  # Caminho correto para o arquivo .zip
    deploymentMethod: 'auto'